// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package turso

import (
	"context"
	"reflect"

	"github.com/pierskarsenbarg/pulumi-turso/sdk/go/turso/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Your Turso API token
	ApiToken pulumix.Output[*string] `pulumi:"apiToken"`
	// Organisation name
	OrganizationName pulumix.Output[*string] `pulumi:"organizationName"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiToken == nil {
		if d := internal.GetEnvOrDefault("", nil, "TURSO_APITOKEN"); d != nil {
			args.ApiToken = pulumix.Ptr(d.(string))
		}
	}
	if args.OrganizationName == nil {
		if d := internal.GetEnvOrDefault("", nil, "TURSO_ORGANISATIONNAME"); d != nil {
			args.OrganizationName = pulumix.Ptr(d.(string))
		}
	}
	if args.ApiToken != nil {
		untypedSecretValue := pulumi.ToSecret(args.ApiToken.ToOutput(ctx.Context()).Untyped())
		args.ApiToken = pulumix.MustConvertTyped[*string](untypedSecretValue)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:turso", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Your Turso API token
	ApiToken *string `pulumi:"apiToken"`
	// Organisation name
	OrganizationName *string `pulumi:"organizationName"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Your Turso API token
	ApiToken pulumix.Input[*string]
	// Organisation name
	OrganizationName pulumix.Input[*string]
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func (o ProviderOutput) ToOutput(ctx context.Context) pulumix.Output[Provider] {
	return pulumix.Output[Provider]{
		OutputState: o.OutputState,
	}
}

// Your Turso API token
func (o ProviderOutput) ApiToken() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.ApiToken })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

// Organisation name
func (o ProviderOutput) OrganizationName() pulumix.Output[*string] {
	value := pulumix.Apply[Provider](o, func(v Provider) pulumix.Output[*string] { return v.OrganizationName })
	return pulumix.Flatten[*string, pulumix.Output[*string]](value)
}

func init() {
	pulumi.RegisterOutputType(ProviderOutput{})
}
