// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pierskarsenbarg/pulumi-turso/sdk/go/turso/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Your Turso API token
func GetApiToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "turso:apiToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "TURSO_APITOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Organisation name
func GetOrganizationName(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "turso:organizationName")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "TURSO_ORGANISATIONNAME"); d != nil {
		value = d.(string)
	}
	return value
}
